services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: 
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8080:8080"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: docker-spring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d docker-spring"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - s-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  s-network:
    driver: bridge
volumes:
  postgres-s-data:
